name: Main

on: [push]

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Run Type Check & Linters
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check types
        run: pnpm type-check

      - name: Check linting
        run: pnpm lint

      - name: Run tests
        run: pnpm test:ci

      - name: Build storybook
        run: pnpm build-storybook

      - name: Build package
        run: pnpm build

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v5
